spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/commitcard}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.forward-headers-strategy=native

github.api.token=${GITHUB_TOKEN:}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_OAUTH_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_OAUTH_CLIENT_SECRET:}
debug=true